---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: sewa2029
    group_name: cloud 
  vars_files:
    - variables.yml
  tasks:
    - name: check the time
      command: dateabbaba
#      when: ansible_distribution == "sewa" or ansible_processor_nproc == 2
    - name: create user sewa
      user:
        name: "{{user_name}}"
        comment: Sewa DevOps
    - name: create group
      group:
        name: "{{group_name}}"
        state: present
    - name: install package
      package:
        name: "{{pkg_name}}"
        state: present